name: Docker Image CI

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  test-build-and-publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the repository
        uses: actions/checkout@v3
      - name: Run Tests
        run: make test
      - name: Build the Docker image
        if: github.event_name == 'push' && github.event.pull_request.merged == true
        run: make image
      - name: Push the Docker image
        if: github.event_name == 'push' && github.event.pull_request.merged == true
        run: make push
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
